Factories:
    - class_name: UtilFactory
      kwargs:
        module: Cropper
        left: 0
        right: 0
        top: 35
        bottom: 0
    - class_name: UtilFactory
      kwargs:
        module: Resizer
        width: 96
        height: 96
    - class_name: UtilFactory
      kwargs:
        module: MinMaxNormalizer
        min_: 0
        max_: 255
    - class_name: CVModuleFactory
      kwargs: 
        Optimizer:
            class_name: CMAES
            kwargs:
                n_params: 150
                lambda_: 50
                mean: 0
                std: 0.1
        CVModule:
            class_name: ConvolutionModule
            kwargs:
                n_filters: 2
                filter_sizes: 5
    - class_name: DecisionTreeFactory
      kwargs:
        Optimizer:
            class_name: GeneticProgramming
            kwargs:
                pop_size: 50
                cx_prob: 0
                mut_prob: 1
                tournament_size: 10
                bounds:
                    float:
                        type: float
                        min: 0
                        max: 96
                    input_index:
                        type: int
                        min: 0
                        max: 4
                    action:
                        type: int
                        min: 0
                        max: 4
                max_depth: 4
                elitist: true
        DecisionTree:
            gamma: 0
        ConditionFactory:
            # Not used with GP
            type: orthogonal
        LeafFactory:
            class_name: ConstantLeafFactory
            kwargs:
                n_actions: 4
    - class_name: UtilFactory
      kwargs:
        module: OneHotEncoder        
        n_actions: 4

Mapper:
    class: KNNAcceleratedMapper
    kwargs:
        mapper_name: MultiProcessMapper
        k: 5
        max_dist: 5
        n_samples: 100
        env_name: "Pong-v0"
        n_jobs: -1

PipelineFactory:
    class: CartesianProductPipelineFactory
    config:
        aggregation_fcn: max

EvolutionaryProcess:
    generations: 100

Fitness:
    seeding: False # Faster
    episode_length: null # no constraints
    early_stopping:
        action_patience: null
        threshold: -7
        assign: -21
        positive_patience: null
    render: False
    env_name: Pong-v0
    n_episodes: 3
    env_kwargs: {}
    cropping: [35, 0, 0, 0]
    env_params: 
        - frameskip: [1, 2]
